### ISSUE TITLE
Geometry seems off (3D BAG)

### ISSUE THREAD

**Issue by jpvanmuijen** [Geodan/pg2b3dm#114] opened 2023-09-11 08:50 UTC
Hi, 

We are trying to create 3D Tiles from the [3D BAG GeoPackage](https://3dbag.nl/en/download). Converting the gpkg to PostGIS and converting to tiles works perfectly fine, but the geometry seems off in a lot of places. 

Cesium JS seems to automatically correct this by making the material 2-sided by default. However, in Cesium for Unity and Unreal, the material is 1-sided by default and all kinds of gaps appear. I checked the geometry in 3ds Max, and it seems like the normals on random places are flipped inside out. 

1. CesiumJS, which corrects the normals by making the material double sided (I assume); 

<img width="1098" alt="image" src="https://github.com/Geodan/pg2b3dm/assets/13887103/12a08d2d-290e-496f-b491-2aba352ff9c9">

3. Cesium for Unity, with the default 1-sided material (same for Unreal); 

<img width="776" alt="image" src="https://github.com/Geodan/pg2b3dm/assets/13887103/2fe2d6e0-32be-4f94-b8e8-78e6204e9a91">
<img width="774" alt="image" src="https://github.com/Geodan/pg2b3dm/assets/13887103/8d9a6fe2-80de-4af6-b890-35d7c7e5a3fc">

5. Cesium for Unity, with material switched to 2-sided (same for Unreal); 

<img width="775" alt="image" src="https://github.com/Geodan/pg2b3dm/assets/13887103/d335edd2-02b5-4c45-869c-54636733c1bf">
<img width="775" alt="image" src="https://github.com/Geodan/pg2b3dm/assets/13887103/87e4e12d-e1eb-4ea9-b884-d89ef41265e9">

7. GLTF (converted from b3dm) in Babylon Sandbox, Backface culling switched on; 

<img width="651" alt="image" src="https://github.com/Geodan/pg2b3dm/assets/13887103/4e893aa6-4161-4e6a-8811-5716e78897f9">

9. Faces selected in 3ds Max, where the darker ones (specifically the one on the outside of the building) are inside out; 

<img width="405" alt="image" src="https://github.com/Geodan/pg2b3dm/assets/13887103/a89daab2-5ba2-48ca-b8fc-93f9978d5ca6">

Attached are the files that I used for these screenshots. Not sure if all of these are useful, but just to be thorough. 
[8_53_103..zip](https://github.com/Geodan/pg2b3dm/files/12574003/8_53_103.zip)

Could you maybe have a look and provide some guidance as to how we can use the 3D BAG as input for this tool? It could well be that the source geometry is off, in which case we probably should just switch to a 2-sided material for our applications. But that might have an impact on performance, and we'd prefer to not take any shortcuts. 

If you need any additional information or testing, please do let me know. 

Thanks!

**Comment by jpvanmuijen** [comment] 2023-09-11 12:09
Some additional info; I followed the steps as described in [README.MD](https://github.com/Geodan/pg2b3dm/blob/master/README.md) using a [single tile](https://3dbag.nl/nl/download?tid=7-480-624) in the same area. The result is the same as before; Cesium for Unity showing gaps and CesiumJS apparently correcting this. 
(Weird side note is the location of the buildings has shifted in both applications)

<img width="778" alt="image" src="https://github.com/Geodan/pg2b3dm/assets/13887103/ee2d7eb6-37c4-4bc2-89ba-99a77b9d7649">

<img width="778" alt="image" src="https://github.com/Geodan/pg2b3dm/assets/13887103/75b4e1f5-40fd-4b24-8fd1-aaf4ebaff619">

**Comment by bertt** [comment] 2023-09-18 17:59
Hi, I can reproduce the effect of missing polygons in CesiumJS when using  DoubleSided = false

![image](https://github.com/Geodan/pg2b3dm/assets/538812/ca9e5bfc-453d-4973-a147-9c22f03f2ffc)

Notes: 

- The default value of DoubleSided in glTF is false, in pg2b3dm DoubleSided is set to true in the current version (when not using custom shaders). I suspect the source data, as the triangulation keeps the original polygon normals;

- The horizontal offset I cannot reproduce, maybe this is something related to the used basemap.

So for the moment I would advise to keep the DoubleSided = true

**Comment by jpvanmuijen** [comment] 2023-09-21 08:07
Hi, 

The offset is something that happened once, so I guess we can ignore that. I used the tile just south of the one you mentioned, https://3dbag.nl/nl/download?tid=9-316-512 

Main takeaway is that the triangulation keeps the original normals, so we can rule out any errors during conversion. That's great. 
So we will try to; 
1. Get the source data as clean as possible;
2. Correct any remaining errors with materials/shaders. 

Thanks for checking and getting back to me!

**Comment by bertt** [comment] 2023-09-26 14:22
I've created a new release 1.8.1, can you try? There is a new option double-sided (default true), but I got the impression Cesium for Unity3D does not handle this glTF option correctly.

**Comment by jpvanmuijen** [comment] 2023-09-28 13:02
Hi - I just tested with the 1.8.1 version which appears to be working fine :ok_hand: 
_(the implicit/explicit option somehow didn't work for me in version 1.7.1 but that seems to be fixed)_
Delighted to see that you added support for gLTF and Structured Metadata as well! 

We have concluded that there are some incorrect faces in both the 3D BAG and our own data, given that there's still flipped normals in our resulting geometry. 
Also, I think Unity handles the shading of the 2-sided material a bit wonky. Attached is a side by side comparison of a 1- and 2-sided material. I suppose this could be fixed by tweaking the shader. 

![image](https://github.com/Geodan/pg2b3dm/assets/13887103/edf3253a-f482-453d-9d6f-02185109cdac)

![image](https://github.com/Geodan/pg2b3dm/assets/13887103/b9802c3b-5232-4c7f-969a-46bfba43a3d2)

The issues seem to apply to the flat roof surfaces in particular. 
Again, assuming the triangulation keeps the original normals, somehow there are still errors in our source data. 

CesiumJS and Unreal seem to do a better job at the 2-sided shader. 

![image](https://github.com/Geodan/pg2b3dm/assets/13887103/fc83b51a-75c8-4261-b856-0059b0c39354)

![image](https://github.com/Geodan/pg2b3dm/assets/13887103/4e907000-6afa-4804-b227-0a9512bec009)

![image](https://github.com/Geodan/pg2b3dm/assets/13887103/16fd24bb-d796-4205-8b4f-ac58b51e9557)

All in all, I think we can work with the current setup and output. 

Let me know if you need any additional information or testing.

**Comment by bertt** [comment] 2023-09-28 14:16
ok great,

I've found a case in 3D bag (NL.IMBAG.Pand.0289100000000381 near Wageningen) where 2 adjacent flat roofs in a multipolygon (polygon 20/21)  in 7-624-528.gpkg have different orientation (western part CW, eastern part CCW):

![image](https://github.com/Geodan/pg2b3dm/assets/538812/fac6135e-1ad6-401e-9769-50b7d82c310b)

western part:

```
POLYGON Z ((
172934.328125 441146.65625 21.386999130249023,
172932.515625 441195.90625 21.39299964904785,
172932.84375 441195.90625 21.39299964904785,
172932.75 441198.09375 21.39299964904785,
172932.4375 441198.0625 21.39299964904785,
172932.4375 441198.15625 21.39299964904785,
172907.96875 441197.21875 21.38599967956543,
172910.3125 441136.0625 21.378000259399414,
172935.09375 441137.09375 21.38599967956543,
172934.734375 441146.6875 21.386999130249023,
172934.328125 441146.65625 21.386999130249023))
```

eastern part:

```
POLYGON Z ((
172932.515625 441195.90625 18.058000564575195,
172934.328125 441146.65625 18.07200050354004,
172934.734375 441146.6875 18.07200050354004,
172934.625 441149.15625 18.070999145507812,
172935.59375 441149.1875 18.070999145507812,
172935.6875 441146.71875 18.070999145507812,
172947.203125 441147.21875 18.069000244140625,
172945.296875 441196.46875 18.05500030517578,
172933.796875 441196.03125 18.058000564575195,
172933.921875 441192.9375 18.05900001525879,
172932.953125 441192.90625 18.05900001525879,
172932.84375 441195.90625 18.058000564575195,
172932.515625 441195.90625 18.058000564575195))
```

So maybe we can report it at 3D Bag somewhere?

About Unity3D: I did some experiments, it looks like it ignores the doubleSided = true option somehow.

**Comment by bertt** [comment] 2023-09-28 15:25
see also https://github.com/CesiumGS/cesium-unity/issues/370

**Comment by bertt** [comment] 2023-10-03 10:23
Did an experiment with reversing the polygon vertices winding order (when order is wrong), but it's not so trivial to get it right for more complex buildings. So the options are getting doubleSided working and/or fix the winding order in the data.

Closing this issue.

**Closed by bertt** 2023-10-03 10:23 UTC
