### ISSUE TITLE
Bug report:  0_0_0.subtree failed to load in CesiumJS

### ISSUE THREAD

**Issue by IoannaTsakalakidou** [Geodan/pg2b3dm#103] opened 2023-07-18 09:13 UTC
### Description

Unable to load 3D tiles in CesiumJS. In the console the message shows the following: 
<img src="https://github.com/Geodan/pg2b3dm/assets/134394241/87a266c0-df75-4c25-ac57-f8bf74bee50e" width="600" height="300" />

### Possible problem source 
* Opened the `.subtree` files in a text editor
* Compared older files that load as expected with the ones that do not load
* Found char `@`  in file `0_0_0.subtree`  (see image below) and a space char in the rest of the subtree files

<img src="https://github.com/Geodan/pg2b3dm/assets/134394241/d21e4a84-60c7-45dd-8c79-5f3cb4e97a06" width="600" height="400" />

**Comment by bertt** [comment] 2023-07-18 09:57
Hi, how can this be reproduced?

**Comment by IoannaTsakalakidou** [comment] 2023-07-18 11:48
> Hi, how can this be reproduced?

I will provide the dataset I am using as input. Could I have an email address to share the files?

**Comment by bertt** [comment] 2023-07-18 11:58
bert.temme(at)gmail.com

**Comment by bertt** [comment] 2023-07-20 09:59
closing issue because not reproducible

**Closed by bertt** 2023-07-20 09:59 UTC
