### ISSUE TITLE
0 Tiles Created

### ISSUE THREAD

**Issue by elwoodhouse** [Geodan/pg2b3dm#127] opened 2023-11-12 00:39 UTC
Hi,

I just getting started in the 3D Tile space and not sure if my input data is in scope for the pg2b3dm tool or it's not valid data.

I have followed the getting started steps with the 7-480-624.gpkg data and can get a successful result (viewable in new QGIS version by using the --create_gltf false --use_implicit_tiling false flags) but when I try with my data I don't get any tiles created:

`pg2b3dm -h localhost -U postgres -c geom -d postgis_dev -t tbl_xxx -a holder -o D:/Temp/b3dm/xxx --create_gltf false --use_implicit_tiling false --boundingvolume_heights 0,150
Tool: pg2b3dm 1.8.4.0
Password for user postgres:
Start processing 2023-11-12T11:03:05....
Input table: tbl_xxx
Input geometry column: geom
Spatial reference of tbl_xxx.geom: 4978
Spatial index detected on tbl_xxx.geom
Query bounding box of tbl_xxx.geom...
Bounding box for tbl_xxx.geom (in WGS84): -86.4722, 16.3666, -86.4714, 16.3677
Default color: #FFFFFF
Default metallic roughness: #008000
Doublesided: True
Create glTF tiles: False
Attribute columns: holder
Starting Cesium mode...
Translation: 376706.25,-6109692.5,1785745.625
Lod column:
Geometric errors: 2000,0
Refinement: REPLACE
Geometric errors used: 2000,0
Heights for bounding volume: [0 m, 150 m]
Add outlines: False
Use 3D Tiles 1.1 implicit tiling: False
Maximum features per tile: 1000
Start generating tiles...

Tiles created: 0

Elapsed: 510 milliseconds
Program finished 2023-11-12T11:03:06.`

As far as I can tell my input data is valid, it's a POLYHEDRALSURFACE Z shape resulting from a ST_3DConvexHull(ST_Collect(ST_Transform(f.geom, 4978))). It's quite detailed, it's 100x the size of the shapes in the 7-480-624 dataset. The bounding box reported in output above is accurate. Is there a way I can tell why it's not being tiled?

Edit: Reading up on the 4978 coordinate system, I'm not sure I'm converting the z values successfully into the 4978 format. My shapes start with 376714.59751021146 -6109828.795406355 1785756.9369908173,376715.58128376666 -6109828.453054279 1785757.894337335,...

Thanks (and thanks for the tool).
Leon.

**Comment by bertt** [comment] 2023-11-12 09:13
can you try without ST_Collect?

**Comment by elwoodhouse** [comment] 2023-11-13 09:25
Without the ST_Collect or ST_3DConvexHull and limiting the geometry to one input, I get the same result. This is the geometry as text:
POLYHEDRALSURFACE Z (((376670.02637522196 -6109722.220358767 1785759.4000501197,376670.01162139577 -6109721.938838985 1785760.359873125,376671.01013288565 -6109721.878013012 1785760.3573811539,376671.02488671034 -6109722.159532793 1785759.39755815,376670.02637522196 -6109722.220358767 1785759.4000501197)),((376670.08541567955 -6109723.1780160535 1785759.6818421404,376671.08392732445 -6109723.117190071 1785759.6793501703,376671.06917349744 -6109722.835670246 1785760.6391733254,376670.0706618511 -6109722.896496229 1785760.641665297,376670.08541567955 -6109723.1780160535 1785759.6818421404)),((376670.02637522196 -6109722.220358767 1785759.4000501197,376670.08541567955 -6109723.1780160535 1785759.6818421404,376670.0706618511 -6109722.896496229 1785760.641665297,376670.01162139577 -6109721.938838985 1785760.359873125,376670.02637522196 -6109722.220358767 1785759.4000501197)),((376671.02488671034 -6109722.159532793 1785759.39755815,376671.01013288565 -6109721.878013012 1785760.3573811539,376671.06917349744 -6109722.835670246 1785760.6391733254,376671.08392732445 -6109723.117190071 1785759.6793501703,376671.02488671034 -6109722.159532793 1785759.39755815)),((376670.02637522196 -6109722.220358767 1785759.4000501197,376671.02488671034 -6109722.159532793 1785759.39755815,376671.08392732445 -6109723.117190071 1785759.6793501703,376670.08541567955 -6109723.1780160535 1785759.6818421404,376670.02637522196 -6109722.220358767 1785759.4000501197)),((376670.01162139577 -6109721.938838985 1785760.359873125,376670.0706618511 -6109722.896496229 1785760.641665297,376671.06917349744 -6109722.835670246 1785760.6391733254,376671.01013288565 -6109721.878013012 1785760.3573811539,376670.01162139577 -6109721.938838985 1785760.359873125)))

**Comment by bertt** [comment] 2023-11-13 10:48
Ok, I can reproduce it with a new table with 1 geometry (your polyhedral). I think the issue is that when there is a table with the geometries on 1 position pg2b3dm does not select it. Normally there are more geometries on different locations in the table.

FYI: First the geometries are counted using sql like: 

```
select count(geom) from issue127 where ST_Intersects(ST_Centroid(ST_Envelope(geom)), ST_Transform(ST_MakeEnvelope(-86.4722, 16.3666, -86.4714, 16.3677, 4326), 4978)) 	
```

If this query returns 0, no glTF's will be created.

So as a workaround you can try to add some geometries on a different location and try again.

**Comment by bertt** [comment] 2023-11-13 11:51
I've created 1.8.5, can you try with this version?

**Comment by elwoodhouse** [comment] 2023-11-14 09:15
Thanks for the quick update.

1.8.5 is an improvement. If I limit the number of records in the ST_3DConvexHull(ST_Collect(geom)) to 6 or less, a tile is created and I can add it into QGIS and see it in the 3D map.

If I increase the number of records in the ST_3DConvexHull(ST_Collect(geom)) to 7 or more I get the 0 Tiles Created result again.

Do I need to set some of the flags to non-default values to overcome this limit? This is the geometry of the 7 aggregated shapes that doesn't tile:
POLYHEDRALSURFACE Z (((376671.43817100936 -6109728.8631337425 1785761.3701022917,376671.42341716844 -6109728.5816136515 1785762.3299263548,376670.424904583 -6109728.642439691 1785762.3324183288,376671.43817100936 -6109728.8631337425 1785761.3701022917)),((376670.424904583 -6109728.642439691 1785762.3324183288,376670.3658641277 -6109727.684782448 1785762.050626157,376670.43965842546 -6109728.923959782 1785761.372594264,376670.424904583 -6109728.642439691 1785762.3324183288)),((376670.43965842546 -6109728.923959782 1785761.372594264,376671.43817100936 -6109728.8631337425 1785761.3701022917,376670.424904583 -6109728.642439691 1785762.3324183288,376670.43965842546 -6109728.923959782 1785761.372594264)),((376671.01013288565 -6109721.878013012 1785760.3573811539,376671.02488671034 -6109722.159532793 1785759.39755815,376670.01162139577 -6109721.938838985 1785760.359873125,376671.01013288565 -6109721.878013012 1785760.3573811539)),((376670.02637522196 -6109722.220358767 1785759.4000501197,376670.0706618511 -6109722.896496229 1785760.641665297,376670.01162139577 -6109721.938838985 1785760.359873125,376670.02637522196 -6109722.220358767 1785759.4000501197)),((376670.26253705256 -6109726.050987919 1785760.5272182021,376670.1444561372 -6109724.135673342 1785759.963634161,376670.02637522196 -6109722.220358767 1785759.4000501197,376670.26253705256 -6109726.050987919 1785760.5272182021)),((376671.42341716844 -6109728.5816136515 1785762.3299263548,376671.2462953329 -6109725.708641948 1785761.4845498402,376670.424904583 -6109728.642439691 1785762.3324183288,376671.42341716844 -6109728.5816136515 1785762.3299263548)),((376670.43965842546 -6109728.923959782 1785761.372594264,376671.3791303953 -6109727.905476465 1785761.0883102715,376671.43817100936 -6109728.8631337425 1785761.3701022917,376670.43965842546 -6109728.923959782 1785761.372594264)),((376670.3658641277 -6109727.684782448 1785762.050626157,376670.3806179678 -6109727.9663024945 1785761.0908022434,376670.43965842546 -6109728.923959782 1785761.372594264,376670.3658641277 -6109727.684782448 1785762.050626157)),((376670.02637522196 -6109722.220358767 1785759.4000501197,376671.32008978113 -6109726.947819186 1785760.806518251,376670.26253705256 -6109726.050987919 1785760.5272182021,376670.02637522196 -6109722.220358767 1785759.4000501197)),((376670.0706618511 -6109722.896496229 1785760.641665297,376670.1297023064 -6109723.854153472 1785760.923457469,376670.01162139577 -6109721.938838985 1785760.359873125,376670.0706618511 -6109722.896496229 1785760.641665297)),((376670.3658641277 -6109727.684782448 1785762.050626157,376670.1297023064 -6109723.854153472 1785760.923457469,376670.0706618511 -6109722.896496229 1785760.641665297,376670.3658641277 -6109727.684782448 1785762.050626157)),((376670.26253705256 -6109726.050987919 1785760.5272182021,376671.32008978113 -6109726.947819186 1785760.806518251,376670.43965842546 -6109728.923959782 1785761.372594264,376670.26253705256 -6109726.050987919 1785760.5272182021)),((376671.32008978113 -6109726.947819186 1785760.806518251,376671.02488671034 -6109722.159532793 1785759.39755815,376671.3791303953 -6109727.905476465 1785761.0883102715,376671.32008978113 -6109726.947819186 1785760.806518251)),((376670.3806179678 -6109727.9663024945 1785761.0908022434,376670.1444561372 -6109724.135673342 1785759.963634161,376670.26253705256 -6109726.050987919 1785760.5272182021,376670.3806179678 -6109727.9663024945 1785761.0908022434)),((376670.43965842546 -6109728.923959782 1785761.372594264,376670.3806179678 -6109727.9663024945 1785761.0908022434,376670.26253705256 -6109726.050987919 1785760.5272182021,376670.43965842546 -6109728.923959782 1785761.372594264)),((376670.3658641277 -6109727.684782448 1785762.050626157,376670.1444561372 -6109724.135673342 1785759.963634161,376670.3806179678 -6109727.9663024945 1785761.0908022434,376670.3658641277 -6109727.684782448 1785762.050626157)),((376671.2462953329 -6109725.708641948 1785761.4845498402,376670.1297023064 -6109723.854153472 1785760.923457469,376670.424904583 -6109728.642439691 1785762.3324183288,376671.2462953329 -6109725.708641948 1785761.4845498402)),((376671.01013288565 -6109721.878013012 1785760.3573811539,376671.2462953329 -6109725.708641948 1785761.4845498402,376671.42341716844 -6109728.5816136515 1785762.3299263548,376671.01013288565 -6109721.878013012 1785760.3573811539)),((376670.424904583 -6109728.642439691 1785762.3324183288,376670.1297023064 -6109723.854153472 1785760.923457469,376670.3658641277 -6109727.684782448 1785762.050626157,376670.424904583 -6109728.642439691 1785762.3324183288)),((376671.42341716844 -6109728.5816136515 1785762.3299263548,376671.3791303953 -6109727.905476465 1785761.0883102715,376671.01013288565 -6109721.878013012 1785760.3573811539,376671.42341716844 -6109728.5816136515 1785762.3299263548)),((376671.43817100936 -6109728.8631337425 1785761.3701022917,376671.3791303953 -6109727.905476465 1785761.0883102715,376671.42341716844 -6109728.5816136515 1785762.3299263548,376671.43817100936 -6109728.8631337425 1785761.3701022917)),((376670.0706618511 -6109722.896496229 1785760.641665297,376670.1444561372 -6109724.135673342 1785759.963634161,376670.3658641277 -6109727.684782448 1785762.050626157,376670.0706618511 -6109722.896496229 1785760.641665297)),((376670.02637522196 -6109722.220358767 1785759.4000501197,376670.1444561372 -6109724.135673342 1785759.963634161,376670.0706618511 -6109722.896496229 1785760.641665297,376670.02637522196 -6109722.220358767 1785759.4000501197)),((376670.1297023064 -6109723.854153472 1785760.923457469,376671.06917349744 -6109722.835670246 1785760.6391733254,376671.01013288565 -6109721.878013012 1785760.3573811539,376670.1297023064 -6109723.854153472 1785760.923457469)),((376670.01162139577 -6109721.938838985 1785760.359873125,376670.1297023064 -6109723.854153472 1785760.923457469,376671.01013288565 -6109721.878013012 1785760.3573811539,376670.01162139577 -6109721.938838985 1785760.359873125)),((376671.3791303953 -6109727.905476465 1785761.0883102715,376671.02488671034 -6109722.159532793 1785759.39755815,376671.01013288565 -6109721.878013012 1785760.3573811539,376671.3791303953 -6109727.905476465 1785761.0883102715)),((376670.43965842546 -6109728.923959782 1785761.372594264,376671.32008978113 -6109726.947819186 1785760.806518251,376671.3791303953 -6109727.905476465 1785761.0883102715,376670.43965842546 -6109728.923959782 1785761.372594264)),((376671.2462953329 -6109725.708641948 1785761.4845498402,376671.06917349744 -6109722.835670246 1785760.6391733254,376670.1297023064 -6109723.854153472 1785760.923457469,376671.2462953329 -6109725.708641948 1785761.4845498402)),((376671.01013288565 -6109721.878013012 1785760.3573811539,376671.06917349744 -6109722.835670246 1785760.6391733254,376671.2462953329 -6109725.708641948 1785761.4845498402,376671.01013288565 -6109721.878013012 1785760.3573811539)),((376671.02488671034 -6109722.159532793 1785759.39755815,376671.2020085528 -6109725.032504629 1785760.2429342107,376670.02637522196 -6109722.220358767 1785759.4000501197,376671.02488671034 -6109722.159532793 1785759.39755815)),((376670.01162139577 -6109721.938838985 1785760.359873125,376671.02488671034 -6109722.159532793 1785759.39755815,376670.02637522196 -6109722.220358767 1785759.4000501197,376670.01162139577 -6109721.938838985 1785760.359873125)),((376671.32008978113 -6109726.947819186 1785760.806518251,376671.2020085528 -6109725.032504629 1785760.2429342107,376671.02488671034 -6109722.159532793 1785759.39755815,376671.32008978113 -6109726.947819186 1785760.806518251)),((376670.02637522196 -6109722.220358767 1785759.4000501197,376671.2020085528 -6109725.032504629 1785760.2429342107,376671.32008978113 -6109726.947819186 1785760.806518251,376670.02637522196 -6109722.220358767 1785759.4000501197)))

Thanks again.

**Comment by bertt** [comment] 2023-11-14 09:40
Ok, I can reproduce this, what happens without st_collect?

**Comment by bertt** [comment] 2023-11-14 20:29
did some more testing, looks like there is a bigger issue going on. Shall investigate it more.

**Comment by elwoodhouse** [comment] 2023-11-15 10:13
Without st_collect, all the shapes are processed individually. I've tried with 100,000 individual records and that tiled fine.
The only problem is that with 300,000 individual records, the amount of data is around 350 times more than when it's aggregated into one record with the ST_3DConvexHull(ST_Collect()) as I only need the outer shape.

Given I'm going to be pushing a lot of data into a web client, I'd like to only take the shape that I need.

**Comment by bertt** [comment] 2023-11-15 10:40
Ok I see, as a workaround for now you can increase the value at https://github.com/Geodan/pg2b3dm/blob/master/src/b3dm.tileset/BoundingBoxRepository.cs#L23 (0.001) and recompile to get the above geometry processed.
In a next major release (2.0) I'm planning to fix it (and some other related issues), it will take some time and will have breaking changes.

**Comment by elwoodhouse** [comment] 2023-11-15 10:43
Sounds good, thanks for the workaround.

**Comment by elwoodhouse** [comment] 2023-11-19 00:00
Hi Bert,

This is more an FYI, I've been testing out putting all ~300k records through the tool and into Cesium. It seems that the tool stops at 138k records and doesn't do the rest:

Tool: pg2b3dm 1.8.5.0
Password for user postgres:
Start processing 2023-11-19T09:08:26....
Input table: xxx
Input geometry column: geom
Spatial reference of xxx.geom: 4978
Spatial index detected on xxx.geom
Query bounding box of xxx.geom...
Bounding box for xxx.geom (in WGS84): -86.4732, 16.3656, -86.4704, 16.3687
Default color: #FFFFFF
Default metallic roughness: #008000
Doublesided: True
Create glTF tiles: False
Attribute columns: holder,acquired_date,expiry_date
Starting Cesium mode...
Translation: 376706.25,-6109692.5,1785745.625
Lod column:
Geometric errors: 2000,0
Refinement: REPLACE
Geometric errors used: 2000,0
Heights for bounding volume: [0 m, 200 m]
Add outlines: False
Use 3D Tiles 1.1 implicit tiling: False
Maximum features per tile: 1000
Start generating tiles...
Creating tile: 2_2_1.b3dm
Tiles created: 138

Elapsed: 23 seconds, 807 milliseconds
Program finished 2023-11-19T09:08:50.

The 3D tiles are in the right place and can be viewed in QGIS and Cesium:

![image](https://github.com/Geodan/pg2b3dm/assets/38488541/f77db0c3-bd13-4efe-a534-05bc0945f407)

I won't be showing this number of shapes in Cesium once the aggregated shape is working, so not looking for a fix on this one but thought you might like to know.

Thanks,
Leon.

**Comment by bertt** [comment] 2024-01-03 16:28
Hi, can you try again with 2.0 (just released)? Don't have to convert to epsg:4978 in this version

**Comment by elwoodhouse** [comment] 2024-01-04 11:29
Will do. Will let you know how it goes. Thanks.

**Comment by elwoodhouse** [comment] 2024-01-06 00:54
Hi Bert, 

It worked a treat. The previous attempt without the ST_3DConvexHull resulted in a tileset 60MB in size (only able to tile less than half the total 300k records).

With v2.0, the single aggregated record tiled successfully and came out at 7KB. It loads into Cesium fast and doesn't lag the map at all now.

![image](https://github.com/Geodan/pg2b3dm/assets/38488541/e98c7c1b-3891-440e-b320-b7f8f9e66ac2)

Thanks so much for the help and turn around time.

Cheers,
Leon.

**Comment by bertt** [comment] 2024-01-06 08:33
Hi Leon, great it works so well! Let me know when you've got something to show with the 3D Tiles.

Closing this issue

**Closed by bertt** 2024-01-06 08:33 UTC
